apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      initContainers:
      - name: make-data-subdirs
        image: busybox
        command: ["sh", "-c", "mkdir -p /exports/webapp/1 /exports/webapp/2 /exports/webapp/3 /exports/webapp/4 /exports/webapp/5 /exports/webapp/6 /exports/webapp/7 /exports/webapp/8 /exports/webapp/9 /exports/webapp/10 /exports/sm/1 /exports/sm/2 /exports/sm/3"]
        volumeMounts:
        - name: mypvc
          mountPath: /exports
      - name: chown-exports-dir
        image: busybox
        command: ["sh", "-c", "chown -R 9999:1000 /exports"]
        volumeMounts:
        - name: mypvc
          mountPath: /exports
      containers:
      - name: nfs-server
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: mypvc
      volumes:
        - name: mypvc
          gcePersistentDisk:
            pdName: appian-nfs-disk
            fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server
