apiVersion: v1
kind: PersistentVolume
metadata:
  name: admin-accdocs1
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.ae.svc.cluster.local
    path: "/webapp/1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: admin-accdocs2
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.ae.svc.cluster.local
    path: "/webapp/2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: admin-accdocs3
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.ae.svc.cluster.local
    path: "/webapp/3"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: admin-mini
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.ae.svc.cluster.local
    path: "/webapp/4"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: admin-models
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.ae.svc.cluster.local
    path: "/webapp/5"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: admin-plugins
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.ae.svc.cluster.local
    path: "/webapp/6"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: admin-process-notes
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.ae.svc.cluster.local
    path: "/webapp/7"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: admin-shared
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.ae.svc.cluster.local
    path: "/webapp/8"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: server-archived-process
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.ae.svc.cluster.local
    path: "/webapp/9"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: server-msg
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.ae.svc.cluster.local
    path: "/webapp/10"
