kind: Service
apiVersion: v1
metadata:
  name: webapp
spec:
  selector:
    appian: webapp
  type: LoadBalancer
  loadBalancerIP: {{STATIC_IP_ADDRESS}}
  sessionAffinity: ClientIP
  ports:
  - port: 80
    targetPort: 8080
