apiVersion: v1
data:
  liveness-probe.sh: |
    #!/bin/bash
    jps | grep ServiceManager && jps | grep Kafka && jps | grep QuorumPeerMain

kind: ConfigMap
metadata:
  name: service-manager-liveness-probe