apiVersion: v1
data:
  readiness-probe.sh: |
    #!/bin/bash
    if [[ $(/usr/local/appian/ae/services/bin/status.sh -p a | egrep "Starting|Stopping|Down|Replaying") ]]; then exit 1; else exit 0; fi

kind: ConfigMap
metadata:
  name: service-manager-readiness-probe