apiVersion: v1
kind: Service
metadata:
  name: search-server
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  selector:
    appian: search-server
  clusterIP: None
  ports:
  - port: 9200
    name: http
  - port: 9300
    name: transport
